Add initial client and server.
MetalMari/chat_go pull request #1
Opened 2022-04-04 08:21 UTC by MetalMari

2022-04-04 13:22 UTC, mmishche requested changes

2022-04-05 14:35 UTC, MetalMari commented on Makefile
> +	protoc --go_out=. --go_opt=paths=source_relative     --go-grpc_out=. --go-grpc_opt=paths=source_relative     chat_protos/chat.proto
Done.

2022-04-06 07:26 UTC, mmishche commented on client/chatclient/chat_client.go
> +}
I believe the method should return the users and the caller will do anything else
Let's imagine that you will implement a new service that will be using the code above, but the service will filter users by the first letter of their name or smth like that not just printing them out

2022-04-06 07:26 UTC, mmishche commented on client/chatclient/chat_client.go
> +}
the same here

2022-04-06 07:26 UTC, mmishche commented on client/chatclient/chat_client.go
> +}
the same

2022-04-06 07:26 UTC, mmishche commented on client/main.go
> +	}
I'd rather move this piece of code to another method and call it a "submitRequest"

2022-04-06 07:26 UTC, mmishche commented on go.mod
> +)
It's okay, it means that packages are used indirect way

2022-04-06 07:26 UTC, mmishche commented on server/main.go
> +		" received message from " + in.Message.LoginFrom}, nil
To make a code a bit easier to understand, I would define a new var and call it "statusMessage" instead concatenate it during defining an instance

2022-04-06 10:05 UTC, MetalMari commented on client/chatclient/chat_client.go
> +}
Thanks, got it. Changed.

2022-04-06 10:05 UTC, MetalMari commented on client/chatclient/chat_client.go
> +}
Done.

2022-04-06 10:05 UTC, MetalMari commented on client/chatclient/chat_client.go
> +}
Done.

2022-04-06 10:05 UTC, MetalMari commented on client/main.go
> +	}
Thanks, done.

2022-04-06 10:08 UTC, MetalMari commented on server/main.go
> +		" received message from " + in.Message.LoginFrom}, nil
Done

2022-04-06 10:30 UTC, mmishche approved these changes

2022-04-06 10:30 UTC, mmishche commented on client/chatclient/chat_client.go
> +	return Users, nil
If you specify variables in the return state, you can write just return

2022-04-06 10:30 UTC, mmishche commented on client/chatclient/chat_client.go
> +	return Status, err
the same as above

2022-04-06 10:30 UTC, mmishche commented on client/chatclient/chat_client.go
> +	return Messages, nil
the same as above

2022-04-06 11:07 UTC, MetalMari commented on client/chatclient/chat_client.go
> +	return Users, nil
Thanks, done.

2022-04-06 11:07 UTC, MetalMari commented on client/chatclient/chat_client.go
> +	return Messages, nil
Done

2022-04-06 11:08 UTC, MetalMari commented on client/chatclient/chat_client.go
> +	return Status, err
Done

2022-04-07 18:19 UTC, MetalMari commented on client/chatclient/chat_client.go
> +	return Messages, nil
Done.

2022-04-12 13:03 UTC, merged